name: Go package

on:
  pull_request:
    paths:
      - app_go/**
      - .github/workflows/app_go.yml

defaults:
  run:
    working-directory: ./app_go

jobs:
  golang:
    runs-on: ubuntu-latest
    defaults:        
      run:
        working-directory: ./app_go

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
    
      - name: Build
        run: go build

      - name: Test
        run: go test -v ./...
      
      - name: Lint
        run: gofmt
